on: [pull_request]

jobs:
    build:
        name: Comment a pull_request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Comment a pull_request
              uses: mb2dev/github-action-comment-pull-request@1.0.0
              with:
                message: "Please make sure to update the relevant documentation if needed [here](https://github.com/evercam/evercam-docs/issues/new?assignee=${{ github.event.pull_request.user.login }}title=${{ github.event.pull_request.title }})."
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                
